make navbar responsive with all devices
Whats-Cookin/trust_claim pull request #145
Opened 2023-05-14 13:39 UTC by AmrNabel

2023-05-18 15:00 UTC, sahdasamier commented on src/components/Navbar/Responsive.tsx
> +  const handleSearch = async () => {
remove junk code

2023-05-18 15:06 UTC, sahdasamier commented on src/containers/Login/index.tsx
> +        <>
{!isSmallScreen && } not using null it is more  better

2023-05-18 15:06 UTC, sahdasamier commented on src/containers/Register/index.tsx
>        <img src={polygon3} alt='' style={{ position: 'absolute', right: '20%', top: '5%', width: '200px' }} />
the same at login too , "about null"

2023-05-18 15:07 UTC, sahdasamier commented on src/containers/Register/index.tsx
>        <img src={polygon3} alt='' style={{ position: 'absolute', right: '20%', top: '5%', width: '200px' }} />
the same at login too , "about null"

2023-05-18 15:07 UTC, sahdasamier commented on src/containers/Search/index.tsx
> +      {isSmallScreen ? (
the same of login and register "about null"

2023-05-18 17:57 UTC, sahdasamier approved these changes

2023-05-19 10:43 UTC, ArnobChowdhury commented on src/containers/Search/index.tsx
> +  const elementWidth = `calc(${windowWidth}px - 50%)`
Don't calculate width like this. Give the search bar the same size as the form in smaller screen.

2023-05-19 10:45 UTC, ArnobChowdhury requested changes
You are repeating the same code in `Login`, `Register`, `Search`. DRY. Make the search bar a different component. And use that component wherever you need to.

2023-05-19 10:52 UTC, ArnobChowdhury commented on src/App.css
> +}
Instead of writing breakpoints like this use the breakpoints given by Material UI.

2023-05-20 16:45 UTC, sahdasamier requested changes
hi Amr, there are some files you deleted as Jason oR composed and another, so please recreate this PR , because there are more conflicts here because of that 
so I will close and sorry for that

2023-05-20 16:45 UTC, closed without merging