update color of nodes
Whats-Cookin/trust_claim pull request #168
Opened 2023-05-27 04:43 UTC by Zakiamangal

2023-05-27 13:15 UTC, sahdasamier approved these changes

2023-05-28 11:48 UTC, sahdasamier requested changes

2023-05-28 11:48 UTC, sahdasamier commented on src/containers/Search/cyConfig.ts
> +          backgroundColor: '#009688',
write primary.main, not his number

2023-05-28 11:48 UTC, sahdasamier commented on src/containers/Search/cyConfig.ts
> +          borderColor: '#009688',
please change to this hover color `#00695f`

2023-05-28 13:19 UTC, sahdasamier approved these changes

2023-05-31 08:05 UTC, arbetamedsarthak approved these changes

2023-05-31 11:29 UTC, merged