update clean code
Whats-Cookin/trust_claim pull request #180
Opened 2023-06-03 08:48 UTC by Zakiamangal

2023-06-03 12:47 UTC, sahdasamier requested changes
the same issue here too, please Zakia any updates should be in the same PR 
don't create new we already have one

2023-06-03 13:55 UTC, Zakiamangal commented
on the previous pr i had red cross and also had error in the bacckend that why i created this

2023-06-03 14:26 UTC, sahdasamier requested changes
i want clean code not removed spaces Zakia ,that is the second time I said that to you

2023-06-07 15:16 UTC, sahdasamier approved these changes

2023-06-07 15:17 UTC, merged