new aspect input
Whats-Cookin/trust_claim pull request #198
Opened 2023-06-15 12:21 UTC by AmrNabel

2023-06-19 21:20 UTC, sahdasamier requested changes

2023-06-19 21:20 UTC, sahdasamier commented on src/components/Chip/Chip.tsx
please please, Amr retype the file to `index.tsx`

2023-06-20 09:14 UTC, AmrNabel commented on src/components/Chip/Chip.tsx
done

2023-06-20 09:15 UTC, AmrNabel commented on src/components/Chip/Chip.tsx
> +          {(personName[0] == 'Quality' || personName.some(item => data.quality.includes(item))) &&
I don't understand

2023-06-20 09:16 UTC, AmrNabel commented on src/components/Chip/Chip.tsx
> +  const [personName, setPersonName] = React.useState<string[]>([])
Done

2023-06-20 09:18 UTC, AmrNabel commented on src/components/Chip/Chip.tsx
> +  const [personName, setPersonName] = React.useState<string[]>([])
Done

2023-06-20 09:18 UTC, AmrNabel commented on src/components/Chip/Chip.tsx
> +          MenuProps={MenuProps}
Done

2023-06-20 09:18 UTC, AmrNabel commented on src/components/Chip/Chip.tsx
> +  PaperProps: {
It is important

2023-06-20 09:19 UTC, AmrNabel commented on src/components/Form/index.tsx
> +const data = {
Done

2023-06-22 10:54 UTC, ArnobChowdhury commented on src/components/Chip/index.tsx
Please change the name of the file. Name it `MultiSelectAspect` or `MultiSelect`. I prefer `MultiSelectAspect` because I don't think this component is reusable.

2023-06-22 10:56 UTC, ArnobChowdhury requested changes
1. When the form is submitted the `aspect`s are not sent with the request body.  
2. Backend expects the aspects to be a single string. Backend is not ready to take an array of aspects.

2023-08-06 16:15 UTC, gvelez17 requested changes
See comments on other multi-select PR, we need to make supporting changes for multiple claims OR change the claim model before we can make this change

2024-05-28 19:07 UTC, closed without merging